    INSERT INTO `adress` (`street`,`floor`,`office`) VALUES ('Talcahuano 550 (Palacio de Tribunales)', 0 , 0);
    INSERT INTO `adress` (`street`,`floor`,`office`) VALUES ('Lavalle 1220 (Cámara Nacional de Apelaciones en Lo Civil)', 0 , 0);
    INSERT INTO `adress` (`street`,`floor`,`office`) VALUES ('Tacuari 138 (Juzgados de la Ciudad(Consejo de la Magistratura)', 0 , 0);
    INSERT INTO `adress` (`street`,`floor`,`office`) VALUES ('Av. Presidente Julio A. Roca 530 (Consejo de la Magistratura)', 0 , 0);
    INSERT INTO `adress` (`street`,`floor`,`office`) VALUES ('Cerrito 538 (Defensioría General de la Nación)', 0 , 0);
    INSERT INTO `adress` (`street`,`floor`,`office`) VALUES ('Tucumán 966 (Ministerio Público Fiscal)', 0 , 0);
    INSERT INTO `adress` (`street`,`floor`,`office`) VALUES ('Libertad 731 (Camara Nacional de Apelaciones en lo Civil y Comercial Federal)', 0 , 0);
    INSERT INTO `adress` (`street`,`floor`,`office`) VALUES ('Roque Saenz Peña 1190 (Defensoría Oficial)', 0 , 0);
    INSERT INTO `adress` (`street`,`floor`,`office`) VALUES ('Paraguay 1536 (Fiscalías en lo Correccional Cap. Fed.)', 0 , 0);
    INSERT INTO `adress` (`street`,`floor`,`office`) VALUES ('Sarmiento 877 (Poder Judicial de la Nación)', 0 , 0);
    INSERT INTO `adress` (`street`,`floor`,`office`) VALUES ('Lavalle 1171 (Camara Nacional De Apelaciones Del Trabajo)', 0 , 0);
